name: Run Python script
on:
  schedule: 
    - cron: '30 9 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
      - name: run script
        run: python main.py stuff
