name: Run Python script
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Run Python script
        run: python3 main.py
