name: Run Python script
on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - '**'
      - '!main'
#   schedule:
#     - cron: '0 1 * * 1-5'
jobs:
  build: # The tag under 'jobs' is what you call to trigger a required check. This could be 'build' or it could be 'test-some-stuff', shouldn't matter.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }} # Calls the matrix strategy above.
      - name: run script
        run: python test.py
  test-some-stuff: # The tag under 'jobs' is what you call to trigger a required check. This could be 'build' or it could be 'test-some-stuff', shouldn't matter.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }} # Calls the matrix strategy above.
      - name: run script
        run: python main.py stuff
